### ISSUE TITLE
Rpush is a ruby application aside from my main rails app using redis

### ISSUE THREAD

**Issue by casertap** [rpush/rpush#184]
I want my rails application to communicate with a simple ruby app running the rpush gem.
I have no problem with the communication part it is just the rpush deamon on my non-rails application that cause me trouble.

I have trouble with rpush when running the command: 
```
$ rpush start -e production

[55, 64] in /Users/pierrecaserta/.rvm/gems/ruby-2.2.1/gems/rpush-2.2.0/lib/rpush/daemon.rb
   55:     end
   56: 
   57:     def self.start
   58:       require 'byebug'
   59:       byebug
=> 60:       Process.daemon if daemonize?
   61:       SignalHandler.start
   62:       initialize_store
   63:       write_pid_file
   64:       Synchronizer.sync
(byebug) continue
````

on Process.deamon it will crash silently so I added:
```
config.embedded = true
````

then 
````
[6, 15] in /Users/pierrecaserta/.rvm/gems/ruby-2.2.1/gems/rpush-2.2.0/lib/rpush/daemon/synchronizer.rb
    6: 
    7:       def self.sync
    8:         apps = Rpush::Daemon.store.all_apps
    9:         require 'byebug'
   10:         byebug
=> 11:         apps.each { |app| sync_app(app) }
   12:         removed = AppRunner.app_ids - apps.map(&:id)
   13:         removed.each { |app_id| AppRunner.stop_app(app_id) }
   14: 
   15:         ProcTitle.update
(byebug) apps
ActiveRecord::ConnectionNotEstablished Exception: No connection pool for Rpush::Client::ActiveRecord::App
(byebug)
`````
apps says No connection pool for rpush

It is not a rails application so my Gemfile
````
source "https://rubygems.org"

gem "activerecord", "4.2.1"
gem 'mysql2', "0.3.17"
gem 'rpush'
gem 'redis'
gem 'byebug'
````

I could run all the migration correctly so all my tables looks good.
I have 1 line on my table rpush_apps
and rpush_notifications are inserted correctly.
database.yml
````
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: rpush
  pool: 5
  username: root
  password: password
  host: localhost

development: &development
  adapter: mysql2
  encoding: utf8mb4
  reconnect: false
  database: rpush
  pool: 5
  username: root
  password: password
  host: localhost

production:
       <<: *development
```

So the problem comes when running the rpush app itself.
I run the rpush app from inside my ruby app (not my rails app).
Do you have any idea?
