### ISSUE TITLE
Daemon health check

### ISSUE THREAD

**Issue by sveredyuk** [rpush/rpush#401]
I have a task to health check rpush daemon periodically. I cannot found anything in source code about status..

**Comment by aried3r** [comment]
> I cannot found anything in source code about status

[Really?](https://github.com/rpush/rpush/search?p=1&q=status&type=&utf8=%E2%9C%93) ;)

I haven't tried accessing that status via Ruby since I run Rpush as a daemon, where I use `rpush status` to check the status.

It should display something like:
```
* Booting Rails 'development' environment...
✔

app_runners:

  app_name: example_app
  queued: 0

  dispatchers:

    0:
      started_at: 2017-07-06T10:31:48+02:00
      dispatched: 565
      thread_status: sleep
```

Hope that helps!
